// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8evnTWPVwZ7FqJMVwJ5kQX
// Component: 2ko9HLxRDvrKgQ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_cbn_components.module.css"; // plasmic-import: 8evnTWPVwZ7FqJMVwJ5kQX/projectcss
import sty from "./PlasmicProviderLogo.module.css"; // plasmic-import: 2ko9HLxRDvrKgQ/css

export type PlasmicProviderLogo__VariantMembers = {};

export type PlasmicProviderLogo__VariantsArgs = {};
type VariantPropType = keyof PlasmicProviderLogo__VariantsArgs;
export const PlasmicProviderLogo__VariantProps = new Array<VariantPropType>();

export type PlasmicProviderLogo__ArgsType = {
  providerLogo?: React.ReactNode;
};

type ArgPropType = keyof PlasmicProviderLogo__ArgsType;
export const PlasmicProviderLogo__ArgProps = new Array<ArgPropType>(
  "providerLogo"
);

export type PlasmicProviderLogo__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultProviderLogoProps {
  providerLogo?: React.ReactNode;
  className?: string;
}

function PlasmicProviderLogo__RenderFunc(props: {
  variants: PlasmicProviderLogo__VariantsArgs;
  args: PlasmicProviderLogo__ArgsType;
  overrides: PlasmicProviderLogo__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__snWms)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/copy_of_copy_of_cbn_components/images/image.png",
              fullWidth: 617,
              fullHeight: 110,
              aspectRatio: undefined
            }}
          />
        ),

        value: args.providerLogo
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProviderLogo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProviderLogo__VariantsArgs;
    args?: PlasmicProviderLogo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProviderLogo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProviderLogo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProviderLogo__ArgProps,
      internalVariantPropNames: PlasmicProviderLogo__VariantProps
    });

    return PlasmicProviderLogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProviderLogo";
  } else {
    func.displayName = `PlasmicProviderLogo.${nodeName}`;
  }
  return func;
}

export const PlasmicProviderLogo = Object.assign(
  // Top-level PlasmicProviderLogo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProviderLogo
    internalVariantProps: PlasmicProviderLogo__VariantProps,
    internalArgProps: PlasmicProviderLogo__ArgProps
  }
);

export default PlasmicProviderLogo;
/* prettier-ignore-end */
