// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8evnTWPVwZ7FqJMVwJ5kQX
// Component: iAwocRK-9KdmRe
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PaymentOption from "../../PaymentOption"; // plasmic-import: V6gUMiYBt2T1-/component

import { useScreenVariants as useScreenVariantsnwCq1TNqK1ZjKa } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: NWCq1TNqK1ZjKa/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_cbn_components.module.css"; // plasmic-import: 8evnTWPVwZ7FqJMVwJ5kQX/projectcss
import sty from "./PlasmicPaymentLogos.module.css"; // plasmic-import: iAwocRK-9KdmRe/css

export type PlasmicPaymentLogos__VariantMembers = {};

export type PlasmicPaymentLogos__VariantsArgs = {};
type VariantPropType = keyof PlasmicPaymentLogos__VariantsArgs;
export const PlasmicPaymentLogos__VariantProps = new Array<VariantPropType>();

export type PlasmicPaymentLogos__ArgsType = {
  slot8?: React.ReactNode;
  slot9?: React.ReactNode;
  slot10?: React.ReactNode;
  slot11?: React.ReactNode;
  slot12?: React.ReactNode;
  slot13?: React.ReactNode;
  slot14?: React.ReactNode;
  slot15?: React.ReactNode;
  slot16?: React.ReactNode;
  slot17?: React.ReactNode;
  slot18?: React.ReactNode;
  slot19?: React.ReactNode;
  slot20?: React.ReactNode;
  slot21?: React.ReactNode;
  slot22?: React.ReactNode;
  slot23?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPaymentLogos__ArgsType;
export const PlasmicPaymentLogos__ArgProps = new Array<ArgPropType>(
  "slot8",
  "slot9",
  "slot10",
  "slot11",
  "slot12",
  "slot13",
  "slot14",
  "slot15",
  "slot16",
  "slot17",
  "slot18",
  "slot19",
  "slot20",
  "slot21",
  "slot22",
  "slot23"
);

export type PlasmicPaymentLogos__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultPaymentLogosProps {
  slot8?: React.ReactNode;
  slot9?: React.ReactNode;
  slot10?: React.ReactNode;
  slot11?: React.ReactNode;
  slot12?: React.ReactNode;
  slot13?: React.ReactNode;
  slot14?: React.ReactNode;
  slot15?: React.ReactNode;
  slot16?: React.ReactNode;
  slot17?: React.ReactNode;
  slot18?: React.ReactNode;
  slot19?: React.ReactNode;
  slot20?: React.ReactNode;
  slot21?: React.ReactNode;
  slot22?: React.ReactNode;
  slot23?: React.ReactNode;
  className?: string;
}

function PlasmicPaymentLogos__RenderFunc(props: {
  variants: PlasmicPaymentLogos__VariantsArgs;
  args: PlasmicPaymentLogos__ArgsType;
  overrides: PlasmicPaymentLogos__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnwCq1TNqK1ZjKa()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__idEa)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img___9GKXc)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot8
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__ibDqm)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__dlIZq)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot9
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption___0PSy)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__dz09U)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot10
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__lDg3P)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__i1NVp)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot11
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__dPVi)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__xhNi)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot12
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__yMo62)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__kwfbX)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot13
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__viS3I)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img___8Uh6I)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot14
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__yrTu9)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__uPgWa)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot15
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "_992") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__etTsA)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__cqm1B)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot16
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? true
          : hasVariant(globalVariants, "screen", "_1044")
          ? true
          : false
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption___3Wl1V)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__byUfA)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot21
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? true
          : hasVariant(globalVariants, "screen", "_1044")
          ? true
          : false
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__cj5Ea)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__xFLeE)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot22
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? true
          : hasVariant(globalVariants, "screen", "_1044")
          ? true
          : false
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__i7BpI)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__x5Chq)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot23
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? true
          : hasVariant(globalVariants, "screen", "_1200")
          ? true
          : hasVariant(globalVariants, "screen", "max")
          ? true
          : false
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__gl3F)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__nC2B9)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot19
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? true
          : hasVariant(globalVariants, "screen", "_1200")
          ? true
          : hasVariant(globalVariants, "screen", "max")
          ? true
          : false
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__yC5Cb)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__cz62U)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot20
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(hasVariant(globalVariants, "screen", "max") ? true : true) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption__l4NFx)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__xQhQ1)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot17
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
      {(
        hasVariant(globalVariants, "screen", "_992")
          ? false
          : hasVariant(globalVariants, "screen", "max")
          ? true
          : true
      ) ? (
        <PaymentOption
          className={classNames("__wab_instance", sty.paymentOption___6O7QS)}
          slot8={p.renderPlasmicSlot({
            defaultContents: (
              <p.Stack
                as={p.PlasmicImg}
                hasGap={true}
                alt={""}
                className={classNames(sty.img__h1F6S)}
                displayHeight={"9.844px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"30.359px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
                  fullWidth: 30.359,
                  fullHeight: 9.844,
                  aspectRatio: 3.1
                }}
              />
            ),

            value: args.slot18
          })}
          small={
            hasVariant(globalVariants, "screen", "_1200") ? true : undefined
          }
        />
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPaymentLogos__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPaymentLogos__VariantsArgs;
    args?: PlasmicPaymentLogos__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPaymentLogos__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPaymentLogos__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPaymentLogos__ArgProps,
      internalVariantPropNames: PlasmicPaymentLogos__VariantProps
    });

    return PlasmicPaymentLogos__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPaymentLogos";
  } else {
    func.displayName = `PlasmicPaymentLogos.${nodeName}`;
  }
  return func;
}

export const PlasmicPaymentLogos = Object.assign(
  // Top-level PlasmicPaymentLogos renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPaymentLogos
    internalVariantProps: PlasmicPaymentLogos__VariantProps,
    internalArgProps: PlasmicPaymentLogos__ArgProps
  }
);

export default PlasmicPaymentLogos;
/* prettier-ignore-end */
