// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8evnTWPVwZ7FqJMVwJ5kQX
// Component: V6gUMiYBt2T1-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_cbn_components.module.css"; // plasmic-import: 8evnTWPVwZ7FqJMVwJ5kQX/projectcss
import sty from "./PlasmicPaymentOption.module.css"; // plasmic-import: V6gUMiYBt2T1-/css

export type PlasmicPaymentOption__VariantMembers = {
  small: "small";
};

export type PlasmicPaymentOption__VariantsArgs = {
  small?: SingleBooleanChoiceArg<"small">;
};

type VariantPropType = keyof PlasmicPaymentOption__VariantsArgs;
export const PlasmicPaymentOption__VariantProps = new Array<VariantPropType>(
  "small"
);

export type PlasmicPaymentOption__ArgsType = {
  slot8?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPaymentOption__ArgsType;
export const PlasmicPaymentOption__ArgProps = new Array<ArgPropType>("slot8");

export type PlasmicPaymentOption__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultPaymentOptionProps {
  slot8?: React.ReactNode;
  small?: SingleBooleanChoiceArg<"small">;
  className?: string;
}

function PlasmicPaymentOption__RenderFunc(props: {
  variants: PlasmicPaymentOption__VariantsArgs;
  args: PlasmicPaymentOption__ArgsType;
  overrides: PlasmicPaymentOption__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.rootsmall]: hasVariant(variants, "small", "small") }
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.Stack
            as={p.PlasmicImg}
            hasGap={true}
            alt={""}
            className={classNames(sty.img__xzeOe, {
              [sty.imgsmall__xzeOeSPhR0]: hasVariant(variants, "small", "small")
            })}
            displayHeight={"9px" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"53px" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/copy_of_copy_of_cbn_components/images/frame1889.svg",
              fullWidth: 30.359,
              fullHeight: 9.844,
              aspectRatio: 3.1
            }}
          />
        ),

        value: args.slot8
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPaymentOption__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPaymentOption__VariantsArgs;
    args?: PlasmicPaymentOption__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPaymentOption__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPaymentOption__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPaymentOption__ArgProps,
      internalVariantPropNames: PlasmicPaymentOption__VariantProps
    });

    return PlasmicPaymentOption__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPaymentOption";
  } else {
    func.displayName = `PlasmicPaymentOption.${nodeName}`;
  }
  return func;
}

export const PlasmicPaymentOption = Object.assign(
  // Top-level PlasmicPaymentOption renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPaymentOption
    internalVariantProps: PlasmicPaymentOption__VariantProps,
    internalArgProps: PlasmicPaymentOption__ArgProps
  }
);

export default PlasmicPaymentOption;
/* prettier-ignore-end */
