// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8evnTWPVwZ7FqJMVwJ5kQX
// Component: 2NsBmbW74uTHcu
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_cbn_components.module.css"; // plasmic-import: 8evnTWPVwZ7FqJMVwJ5kQX/projectcss
import sty from "./PlasmicCpaBtn.module.css"; // plasmic-import: 2NsBmbW74uTHcu/css

export type PlasmicCpaBtn__VariantMembers = {};

export type PlasmicCpaBtn__VariantsArgs = {};
type VariantPropType = keyof PlasmicCpaBtn__VariantsArgs;
export const PlasmicCpaBtn__VariantProps = new Array<VariantPropType>();

export type PlasmicCpaBtn__ArgsType = {
  cpaBtn?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCpaBtn__ArgsType;
export const PlasmicCpaBtn__ArgProps = new Array<ArgPropType>("cpaBtn");

export type PlasmicCpaBtn__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCpaBtnProps {
  cpaBtn?: React.ReactNode;
  className?: string;
}

function PlasmicCpaBtn__RenderFunc(props: {
  variants: PlasmicCpaBtn__VariantsArgs;
  args: PlasmicCpaBtn__ArgsType;
  overrides: PlasmicCpaBtn__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "PLAY",
        value: args.cpaBtn,
        className: classNames(sty.slotTargetCpaBtn)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCpaBtn__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCpaBtn__VariantsArgs;
    args?: PlasmicCpaBtn__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCpaBtn__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCpaBtn__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCpaBtn__ArgProps,
      internalVariantPropNames: PlasmicCpaBtn__VariantProps
    });

    return PlasmicCpaBtn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCpaBtn";
  } else {
    func.displayName = `PlasmicCpaBtn.${nodeName}`;
  }
  return func;
}

export const PlasmicCpaBtn = Object.assign(
  // Top-level PlasmicCpaBtn renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCpaBtn
    internalVariantProps: PlasmicCpaBtn__VariantProps,
    internalArgProps: PlasmicCpaBtn__ArgProps
  }
);

export default PlasmicCpaBtn;
/* prettier-ignore-end */
