// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8evnTWPVwZ7FqJMVwJ5kQX
// Component: yyGss2xztyl36
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_cbn_components.module.css"; // plasmic-import: 8evnTWPVwZ7FqJMVwJ5kQX/projectcss
import sty from "./PlasmicCasinoBadge.module.css"; // plasmic-import: yyGss2xztyl36/css

export type PlasmicCasinoBadge__VariantMembers = {};

export type PlasmicCasinoBadge__VariantsArgs = {};
type VariantPropType = keyof PlasmicCasinoBadge__VariantsArgs;
export const PlasmicCasinoBadge__VariantProps = new Array<VariantPropType>();

export type PlasmicCasinoBadge__ArgsType = {
  casinoBadgePlace?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCasinoBadge__ArgsType;
export const PlasmicCasinoBadge__ArgProps = new Array<ArgPropType>(
  "casinoBadgePlace"
);

export type PlasmicCasinoBadge__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCasinoBadgeProps {
  casinoBadgePlace?: React.ReactNode;
  className?: string;
}

function PlasmicCasinoBadge__RenderFunc(props: {
  variants: PlasmicCasinoBadge__VariantsArgs;
  args: PlasmicCasinoBadge__ArgsType;
  overrides: PlasmicCasinoBadge__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__gpQhR)}
            displayHeight={"65px" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"65px" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/copy_of_copy_of_cbn_components/images/group.svg",
              fullWidth: 65,
              fullHeight: 65,
              aspectRatio: 1
            }}
          />
        ),

        value: args.casinoBadgePlace
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCasinoBadge__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCasinoBadge__VariantsArgs;
    args?: PlasmicCasinoBadge__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCasinoBadge__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCasinoBadge__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCasinoBadge__ArgProps,
      internalVariantPropNames: PlasmicCasinoBadge__VariantProps
    });

    return PlasmicCasinoBadge__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCasinoBadge";
  } else {
    func.displayName = `PlasmicCasinoBadge.${nodeName}`;
  }
  return func;
}

export const PlasmicCasinoBadge = Object.assign(
  // Top-level PlasmicCasinoBadge renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCasinoBadge
    internalVariantProps: PlasmicCasinoBadge__VariantProps,
    internalArgProps: PlasmicCasinoBadge__ArgProps
  }
);

export default PlasmicCasinoBadge;
/* prettier-ignore-end */
